import imageCompression from "browser-image-compression";
import { ref, uploadBytes } from "firebase/storage";
import Head from "next/head";
import { ChangeEvent, FormEvent, useState } from "react";
import { storage } from "@/config/FirebaseConfig";
import Image from "next/image";

export default function Home() {
  const [files, setFiles] = useState<File[]>([]);

  const handleAddFiles = (e: ChangeEvent<HTMLInputElement>) => {
    if (!(e.target instanceof HTMLInputElement)) return;

    const value = Array.from(e.target.files!);

    const options = {
      maxSizeMB: 1,
      maxWidthOrHeight: 1920,
      useWebWorker: true,
    };

    value.map(async (file: File) => {
      imageCompression(file, options).then((file: File) => {
        setFiles((prevFiles) => [...prevFiles, file]);
      });
    });
  };

  const onSubmitForm = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!(e.target instanceof HTMLFormElement)) return;

    try {
      files.forEach(async (file: File) => {
        const storageRef = ref(storage, file.name);
        const response = await uploadBytes(storageRef, file);
        return;
      });
      setFiles([]);
      e.target.reset();
    } catch (e) {
      if (e instanceof Error) {
        return e.message;
      }
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={onSubmitForm}>
          <input
            type="file"
            name="file"
            id="file"
            multiple
            onChange={handleAddFiles}
            accept="image/*, .png,.jpg,.jpeg"
            placeholder="Input file"
          />
          <button type="submit">Submit</button>
        </form>
        {files.map((file: File) => {
          return (
            <div key={file.name}>
              <Image width={0} height={0} style={{ width: '6rem', height:'5rem', objectFit: 'cover' }} src={URL.createObjectURL(file)} alt={file.name} />
              <h3>{file.name}</h3>
            </div>
          );
        })}
      </main>
    </>
  );
}
